# Generated by Django 6.0.2 on 2026-03-06 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastelog',
            name='reason',
            field=models.CharField(choices=[('disease', 'Disease'), ('pest', 'Pest Damage'), ('overripe', 'Overripe'), ('weather', 'Weather Damage'), ('poor_growth', 'Poor Growth'), ('spoiled', 'Spoiled'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='scans/%Y/%m/%d/')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('identified_vegetable', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('freshness_status', models.CharField(choices=[('fresh', 'Fresh'), ('good', 'Good — Use Within Days'), ('caution', 'Use Today'), ('spoiling', 'Spoiling'), ('spoiled', 'Spoiled — Discard')], default='fresh', max_length=20)),
                ('freshness_score', models.IntegerField(default=100)),
                ('condition', models.CharField(choices=[('healthy', 'Healthy'), ('wilting', 'Wilting'), ('mouldy', 'Mouldy'), ('bruised', 'Bruised'), ('discoloured', 'Discoloured'), ('pest_damage', 'Pest Damage'), ('disease', 'Disease Detected'), ('unknown', 'Unknown')], default='healthy', max_length=20)),
                ('full_analysis', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('meal_suggestions', models.TextField(blank=True)),
                ('storage_tips', models.TextField(blank=True)),
                ('days_remaining', models.IntegerField(blank=True, null=True)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('vegetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='garden.vegetable')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddField(
            model_name='wastelog',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_logs', to='garden.scanresult'),
        ),
    ]
